### ISSUE TITLE
Document project requirements

### ISSUE THREAD

**Issue by ryantanaka** [erdl/sensors#10]
# WIP

# Requirements for Sensors Project

The requirements for the sensors project will be documented here. This will serve as a proposal draft for the project before any coding begins.

### 1. Project configuration files must be stored in the database.
- state timestamps (when data from some sensor was last successfully uploaded) 
- will use purpose table to figure out what data corresponds to what sensor
### 2. Error logging (and logging in general) must be provided for each project. 
- output errors to file for given project
- output report (execution time, rows inserted, etc.)
### 4. Template Program
- create a template project program so that a user only need to set up the database, and fill in a few variable parameters

**Comment by ryantanaka** [comment]
meeting w/ Eileen 2/26/18 notes:
- discussed database schema 
    - what we should have (https://github.com/erdl/database/blob/master/README.md)
     vs.
    - what Eileen is able to use
    - possible tradeoffs 

- webctrl is fixed in the frog buildings and will not move
    - don't have to worry about knowing where a webctrl sensor was in a prior project when looking
at the reading table

- egauges
    - can be moved
    - can yield different readings depending on how they are set up

TODO: come up with a simple schema incorporating tradeoffs from the way we should do it versus what Eileen is able to use easily and report back to discuss

**Comment by carlosparadis** [comment]
We can re-open this issue if we ever get back to this.
