### ISSUE TITLE
Create minimal code to log VOC and Carbon Dioxide Sensor with Timestamps for Raspberry PI

### ISSUE THREAD

**Issue by carlosparadis** [erdl/sensors#11]
Let's try to start small with these sensor projects so everyone can learn how the data and code will look alike for a future scrape-util utility. I believe we can also explore a lot of details for this particular small project which can serve as prototype documentation for following and more complex ones. 

## Goal

The goal of this issue is to save to the rhasberry pi a .csv file of the following format: 

| timestamp | reading1 | reading2 | reading3 | ... |
| ----- | ---- | ---- | ---- | ---|

For the sensor: 

[Adafruit CCS811 Air Quality Sensor I2C Breakout - VOC & eCO2 - 3v3 & 5v -Arduino](https://www.ebay.com/itm/Adafruit-CCS811-Air-Quality-Sensor-I2C-Breakout-VOC-eCO2-3v3-5v-Arduino/172833181875?hash=item283da910b3:g:XRAAAOSw6WVZnN7v)

![s-l500](https://user-images.githubusercontent.com/17270563/36890129-de0c79a8-1da0-11e8-9435-28fb2f137190.jpg)

and the RTC: 

[DS3231 AT24C32 IIC precision Real time clock RTC memory module](https://www.ebay.com/itm/DS3231-AT24C32-IIC-precision-Real-time-clock-RTC-memory-module-For-Arduino/201478295970?hash=item2ee90ad1a2:g:UA8AAOSwHQ9WYHza)

![rtc](https://user-images.githubusercontent.com/17270563/36890529-57b60d90-1da2-11e8-8194-163914ffb6ac.jpg)

Which Eileen is interested and you already purchased. 

## Code 

Feel reminders here: 

 * Make it clear what is code associated with each component. Here you have 2 parts, but one of them has 2 sensors. It is important we can read your code and make sense which one of them it is interacting with (and preferable why). 
 * The rest of the group doesn't have much background on where to get the code to deal with the sensor. Make sure to document where you got the code, any examples that help you get through, or documentation of the code the sensor may have provided. 
 * If you feel a tiny mistake may lead to fry the entire sensor on the code, make sure to put a lot of red flags. It may not be as obvious to us.  
 * Meaningful variables in the code here will go a long way, especially if you are using hexacode or assembly to specify some pin. I have seen from easy to read to completely gibberish code out there for sensors on Arduino and Pi. **Avoid acronyms and abbreviations, the rest of the group will likely not recognize jargon!**

## Documentation

3 Things: 

   - [ ] **Text**: You don't need to write a book on it, but try to write enough someone from your major can at least replicate, as you saw on the [Air Quality Station](https://www.rigacci.org/wiki/doku.php/doc/appunti/hardware/raspberrypi_air) or Sparkfun's tutorial. Whichever you feel it is more instructive. 
  -  [ ] **Diagram**: http://fritzing.org/home/ 
  -  [ ] **Photos**: A few photos of the actual thing, especially on spots that may be tricky 

If you know any other tool than fritzing, feel free to suggest. 

## Where to put the code 

Create a folder called `rhasberry_pi/voc_co2` in this project. Make sure to also add a README.md with some minimal navigation for us to make sense of inside said folder. 

## Where to put the documentation 

Create a page on the wiki called `rhasberry_pi`. Then create a sub-page to it called `voc_co2`. Add images and documentation there. Feel free to add the files in response to this issue, and then hyperlink them on the wiki, as it appears we can't load images on the wiki but can here. **Do not hyperlink from an outside source, as we may lose the image/files on the long-run**.

**Comment by carlosparadis** [comment]
@jygh98 mentioned there is a `cold start` problem, where the first 5 readings may be biased. We need to check with @eileenpeppard wether she prefers to have biased data in the dataset for post-processing, or if we should go with some rule of thumb to always filter the first few rows when it starts in the code. 

Thoughts?

**Comment by eileenpeppard** [comment]
Hi, guys. It would be preferable if it was filtered before storing data...  Hey, I found GitHub! :)

**Comment by carlosparadis** [comment]
@jygh98 you heard the boss! Here is what I suggest we do: Try to run the code in a few different places to see if the environment has any impact on the decision on how many measurements we should not store on turning on. 

**Keep the data** you generated in these different places **stored** in your computer (as in a "experimental dataset") so it is reproducible your analysis of why X rows would be the safest to be discarded. 

**Maybe doing this experiment is better after you have the entire air quality station going, or at least the environment sensors so we can keep track also if the environment was different.**

Thoughts?
