### ISSUE TITLE
Investigate ideal way to run routines in Rhasberry PI

### ISSUE THREAD

**Issue by carlosparadis** [erdl/sensors#13]
On Arduinos, we usually just it's default IDE to send code to the device to keep it running. It is not clear on the Rhasberry PI, having it's own OS, that a cron.job is the way to go about it. We should investigate if that is the case.

**Comment by jygh98** [comment]
rhasberry pi

**Comment by jygh98** [comment]
As talked about previously, if we are interested in routinely running a script on the raspberry pi it will be optimal according to the raspberry pi documentation to use a cron job.

https://www.raspberrypi.org/documentation/linux/usage/cron.md

**Comment by carlosparadis** [comment]
@ryantanaka a simple crontab tutorial is available on this link!
