### ISSUE TITLE
Identify why Raspberry runs too slow with existing sensors 

### ISSUE THREAD

**Issue by carlosparadis** [erdl/sensors#17]
@jygh98 the PI 3 B+ you bought seems to work fine, but on the old Rasberry 2, using NOOBS v2.81's Rasbian 9 Stretch is too slow (holding an on the terminal make it freeze sometimes and also lag while dragging the mouse.  Running updates also lag it to the point of freezing and requiring a reboot. 

Try to find out a solution to this. We may need to roll back to an older system version of Rasbian. 

See for example: https://www.raspberrypi.org/forums/viewtopic.php?t=208595 

For related discussion. 

Also, see if you can find anything about the end of life support for Jessie, in case you think installing that would be a good idea, and a way for us to obtain it, if possible via NOOBS to keep the setup simple.

**Comment by carlosparadis** [comment]
For reference, 

https://wiki.debian.org/LTS 

Although this may not reflect the Rasbian variant. Some say the Rasbian variant of Jessie may hit end of life on May 2018:

https://www.raspberrypi.org/forums/viewtopic.php?t=182288 

If that is the case, we are semi-doomed lol.

**Comment by carlosparadis** [comment]
I was misled. Jessie also runs slow, but I found the problem: The sensors. After I unplugged them (with it powered off), it started running smoothly again. I didn't want to try my luck on the right GPIO, so I didn't try to plug them back in. 

@jygh98 Any idea, if the fact gpio library is not installed, could make the thing slow? I am surprised just the fact they are connected without any script running is slowing it down. 

I am going to re-install Stretch and see if it runs fine without the sensors.

**Comment by carlosparadis** [comment]
Can confirm on Stretch the pi runs just fine without the sensors plugged. Let me know what you think about y question on gpio library. Still find weird it lags it down without running anything..

**Comment by jygh98** [comment]
Hmm interesting, off the top of my head i cant imagine why that would happen.  But if that is the case then i guess when i start repopulating back the sensors on the raspberry pi maybe i can experiment what caused this slow down.

**Comment by carlosparadis** [comment]
@jygh98 Alright sounds good. Once @ryantanaka put the pi 3 B+ on your desk on a port in erdl, I should be able to sudo and install what you need. 

@kathrynparadis should stop to just drop the spaghetti of sensors (I did not remove any cable from the breadboard or modified. It is "as-is" but does double check in case something fell off. But this issue should not be your top priority (the priority is getting the EMP code from the new sensor going). 

However, Pi 2 will stay in my room since I didn't have time to configure yet. 

I think both of them will only come in the afternoon, so if you could also come later it would work best. 

In the meantime, I suggest you update the wiki with the remaining photos and/or check with ryan how to host the images on the wiki if you don't have anything else to do :)

**Comment by carlosparadis** [comment]
@jygh98 I forgot this was already open. Just update here if you find anything that justifies why previously it did not lag with all the sensor and now does.

**Comment by jygh98** [comment]
I was not able to find any specific reason why the old pi was running slow at the time, but as of now it appears to be running fine.
