### ISSUE TITLE
MATT

### ISSUE THREAD

**Issue by ryantanaka** [erdl/sensors#25]
If all the paperwork goes through, expected start day for Matt will be **5/15 @ 8:00am**

# 1. Matt Tasks 
 - [x] **Task 1: Missing data training**
   - use egauge notebook to get data for a given time period
   - download the data, transform it into a csv, and send it to us 
   - deliverable: csv file (run it yourself so you can just diff it)

 - [x] **Task 2: Python script** (#37)
   - turn the python notebook into a script and take the dates as args
   - should produce the same output as the notebook

 - [ ] **Task 3: Timestamp** (#47)
   - augment the script he previously wrote to write a txt file to disk that contains the state timestamp so that it can be re-read in by the program when it runs again
   - note: not just latest timestamp, APPEND timestamps
   - currently creating some tests to check for overlapping readings

 - [x] **Task 4 (optional if he doesnt have virtual box and ubuntu)**
   - run some crontabs

 - [ ] **Task 5: vagrant** (edited by Carlos)
   - watch Ryan's video on how to use the vagrant box (for details, see Ryan tasks Section 2 below)

 - [ ] **Task 6: Deploy postgres on vagrant or virtual box**
   - now have timestamp stored on the database 
   - should be something like `| sensor id | timestamp | event type (timeout, success, etc)|`

 - [ ] **Task 7** 
   - make a table in local database with csbcd configs so that it can be read (only need IDS don't translate this thing)
   - using as "input": scrape-util config and eileen's sensor info table 

## 1.1 Learning Outcomes 
 - Matt should be able to move to the server and be comfortable with the shell
 - eGauge script + database + cron should be completed

## 1.2 Next Steps 

**rinse and repeat the to-do list of items above for webctrl and HOBO (does not need to follow the same sequence of steps, just focus on getting the task done this time)**

# 2. Ryan Tasks

 - [ ] **Record screencast of survey_display and survey_admin for the group**. 
    - possibly use slides 
    - make this comprehensive
    - tag timestamps for topics 
 - [ ] **Record screen cast on how to use the vagrant box for the group**.
    - Same sub-items items as above.

# 3. Egauge script features to add in future issues
- [ ] relate egauge sensors to their purpose ID using a purpose table
- [ ] create process lock to prevent script from starting to run while previous instance of the same script is still running
- [ ] use argparse module in 'if...main' block to parse any command line arguments
- [ ] creating more unit tests to test for any bugs as they come up
- [ ] replace arrow time library with pendulum (or another time library with more support)
- [ ] create separate scripts to manually add data
- [ ] use a library to add script execution time tracking

**Comment by carlosparadis** [comment]
@ryantanaka @matthew-schultz I formatted the body of the first issue comment above to make it easier to keep track of progress. @ryantanaka Please check the boxes as he progresses.

**Comment by carlosparadis** [comment]
Since the effort for egauge, webctrl and hobo is done, and we are moving to refinements, I am closing this.
