### ISSUE TITLE
Setup a Crontab for the Air Quality and HOBO Raspberry Pi

### ISSUE THREAD

**Issue by jygh98** [erdl/sensors#29]
For the raspberry pi in general, we had to choices in dealing with how we were going to get data from the raspberry pi to our database.  The two options we had was either to create a "smart pi" or "dumb pi", in which the pros and cons simply boils down to whether we would want the pi to do data pushing but lack ssh accessibility or have a computer to scrape each pi for data at the cost of setting up router access for ssh setup.  

We decided to continue with the smart pi option as Eileen figured she would need to visit the various project homes regardless for the HOBOs, so for this we would need to setup crontabs for running the sensor scripts.

**Comment by jygh98** [comment]
@ryantanaka

**Comment by carlosparadis** [comment]
@erdl/dev Should we defer this to after @matthew-schultz is done with the main sensor scripts?

**Comment by jygh98** [comment]
Currently i have set up user specific (jason) crontab on both 2B and 9S, where both crontabs are setup similarly with the only difference being the specific sensor script it is trying to run.  In the user specific crontab file, i have the crontab currently running every minute to execute a shell script in each of the sensor folders.

![screenshot from 2018-05-23 12-55-04](https://user-images.githubusercontent.com/25787662/40455503-efb3057c-5e88-11e8-9267-7d6c09e6c372.png)

The shell script follows a basic template of checking if an existing process is running, if not it will execute the logger script.

**Comment by jygh98** [comment]
The crontab has been set up on both raspberry pi as an user specific job (jason) and has been able to keep the logging script active.

As a reminder, each sensor folder contains the logging program `<sensor>_logger.py` and a shell script `<sensor>_check.sh` that checks for only one instance of the logging program is being run at all times.  This shell script is the one that is placed in the user specfic crontab, not the logging program.
