### ISSUE TITLE
Check with Eileen about sampling rate for the sensors

### ISSUE THREAD

**Issue by jygh98** [erdl/sensors#36]
Need to figure out the measuring interval for the data we are collecting and also setting up an averaging function so that the measurements we are collecting are more accurate.

**Comment by jygh98** [comment]
How often should it store data? 5 minutes
At what interval (granularity) is it sampling data? every second if possible

Because there is going to be a time interval in how often data is stored, Eileen would want us to do a trailing timestamp, where the timestamp in each row of data represents the time data was stored, i.e after 5 minutes has passed, it would take the time then.

**Comment by carlosparadis** [comment]
@jygh98 Post here what you found out before closing the issue :)
