### ISSUE TITLE
Log Max/Min measurements for each time interval 

### ISSUE THREAD

**Issue by jygh98** [erdl/sensors#42]
Along with the average data to be saved, max and min will be also recorded for a recorded timestamp for quality checking. As for storing in the csv, each measurements would be recorded as followed:

timestamp, reading1_min, reading1_avg, reading1_max, reading2_min, reading2_avg, reading2_max,...

**Comment by carlosparadis** [comment]
@jygh98 Could you confirm all sensors have the min,avg,max added? If yes, close this to confirm.

**Comment by jygh98** [comment]
Hey carlos, sorry i should have mentioned but i was waiting for you to accept PR#33 for the minimal code to run the HOBO humidity/temp sensor before pushing this min/max commit for it.  Otherwise this is the last sensor to have min, avg, and max added.
