### ISSUE TITLE
Script that creates sensors database and assigns db & file permissions

### ISSUE THREAD

**Issue by matthew-schultz** [erdl/sensors#65]
Usage: ```python3 init_database.py <database name>```

This script currently should:
- write the database name to ```config.txt```
  - read by other scripts to connect to the database
- create a database and enable db permissions for users 'root' and 'locked_user'
  - create a postgres database using the given argument if it does not already exist
  - create postgres database users 'locked_user' and 'root' if they do not exist
  - grants connection permissions to 'locked_user' and 'root' for that db
  - create tables in the database using table definitions in ```egauge/script/orm_egauge.py```
  - grant permissions on those tables to 'locked_user' and 'root'
  - detect and add project_folder_path to the project table
- enable file permissions for 'root' and 'locked_user'
  - create a user group 'sensors'
  - add 'locked_user' and 'root' to that group
  - change the group of each sensor's ```/script``` directory to the 'sensors' group
  - set read/write access of each sensors ```/script/error.log``` file for 'locked_user'

See https://github.com/erdl/sensors/issues/62 for more info about the initial planning of this script ```init_database.py```

**Comment by carlosparadis** [comment]
Ah, I wish I had seen this before you went through the effort to code it. Oh well, at least we have the code if we ever for some reason I am unaware decide to go back to it in the far future!

**Comment by carlosparadis** [comment]
Closing this since code was merged in.
