### ISSUE TITLE
Create script that schedules crontab jobs for data acquisition

### ISSUE THREAD

**Issue by matthew-schultz** [erdl/sensors#66]
See https://github.com/erdl/sensors/issues/62 for more info about the initial planning of this script ```init_crontab.py```

Usage: ```python3 init_crontab.py```

This script should:

- remove all old jobs in 'locked_user' crontab
- get a list of unique sensor types from sensors database
- for each sensor type
  - create a cron job that runs that sensor's data acquisition script at 5 minute intervals

**Comment by carlosparadis** [comment]
Closing this as code was merged in.
