### ISSUE TITLE
Clean init_database.py and init_crontab.py code 

### ISSUE THREAD

**Issue by carlosparadis** [erdl/sensors#69]
Following from #65 #66, we should clean the comment code. For this issue, don't change any functionality, just refactor the code so it is more readable. We will work on the functionality on a separate issue to keep changes and issues small now that we have a functional version. 

Note the priority I am setting things, it is a suggestion of order to handle the issues, but feel free to do in any other way.

**Comment by matthew-schultz** [comment]
Notes from 5/24

Prioritize finishing this issue in the next week

**Comment by matthew-schultz** [comment]
Going to close this issue since its related PR #79 was accepted
