### ISSUE TITLE
Edit on the wiki how to download data to a computer using the Python Script for Egauge

### ISSUE THREAD

**Issue by kathrynparadis** [erdl/sensors#8]
Figure out how to download data to a computer using the Python notebook for Egauge, and create a how-to for it.

**Comment by carlosparadis** [comment]
Not upload, it is only for downloading the data to your computer. Title and description need to be fixed here.

**Comment by carlosparadis** [comment]
I'm closing this, as at the time replace Scrape-utils was not on the table.
