### ISSUE TITLE
Add HOBO Section to wiki explaining how to parse data

### ISSUE THREAD

**Issue by kathrynparadis** [erdl/sensors#9]
Include information in each of the Hobo sections to include the three subsections that the other sections have: Checking data source for data, Manual download, Script download.

**Comment by carlosparadis** [comment]
@kathrynparadis I've linked you a few issues that can be used as material to write the wiki section.

**Comment by carlosparadis** [comment]
I'm closing this, as at the time replace Scrape-utils was not on the table.
